In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("recoverai_payment_recovery_dataset.csv")

# First 5 rows
df.head()

,payment_id,amount,payment_method,failure_reason,previous_successful_payments,previous_failed_payments,retry_count,customer_success_rate,hour_of_payment,customer_tenure_days,recovery_action,recovered,recovered_amount
0,PAY_00001,5472,UPI,Insufficient Funds,6,1,2,0.750,8,502,Reminder,0,0
1,PAY_00002,3090,UPI,User Abandoned,7,1,2,0.778,17,179,UPI Link,1,3090
2,PAY_00003,1858,UPI,Insufficient Funds,6,0,0,0.857,6,477,UPI Link,0,0
3,PAY_00004,510,UPI,Network Error,8,3,0,0.667,22,1331,UPI Link,0,0
4,PAY_00005,1059,Wallet,Bank Timeout,8,1,1,0.800,18,570,UPI Link,1,1059

In [2]:
# Dataset shape
print("Shape:", df.shape)

# Column names
print("\nColumns:")
print(df.columns)

# Dataset information
print("\nDataset Info:")
df.info()

Shape: (5000, 13)

Columns:
Index(['payment_id', 'amount', 'payment_method', 'failure_reason',
       'previous_successful_payments', 'previous_failed_payments',
       'retry_count', 'customer_success_rate', 'hour_of_payment',
       'customer_tenure_days', 'recovery_action', 'recovered',
       'recovered_amount'],
      dtype='str')

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   payment_id                    5000 non-null   str
 1   amount                        5000 non-null   int64
 2   payment_method                5000 non-null   str
 3   failure_reason                5000 non-null   str
 4   previous_successful_payments  5000 non-null   int64
 5   previous_failed_payments      5000 non-null   int64
 6   retry_count                   5000 non-null   int64
 7   customer_success_rate         5000 non-null   float64
 8   hour_of_payment               5000 non-null   int64
 9   customer_tenure_days          5000 non-null   int64
 10  recovery_action               5000 non-null   str
 11  recovered                     5000 non-null   int64
 12  recovered_amount              5000 non-null   int64
dtypes: float64(1), int64(8), str(4)
memory usage: 507.9 KB

In [3]:
# Check all columns properly

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nDataset Info:")
df.info()

print("\nFirst 5 rows:")
display(df.head())

Shape: (5000, 13)

Columns:
['payment_id', 'amount', 'payment_method', 'failure_reason', 'previous_successful_payments', 'previous_failed_payments', 'retry_count', 'customer_success_rate', 'hour_of_payment', 'customer_tenure_days', 'recovery_action', 'recovered', 'recovered_amount']

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   payment_id                    5000 non-null   str
 1   amount                        5000 non-null   int64
 2   payment_method                5000 non-null   str
 3   failure_reason                5000 non-null   str
 4   previous_successful_payments  5000 non-null   int64
 5   previous_failed_payments      5000 non-null   int64
 6   retry_count                   5000 non-null   int64
 7   customer_success_rate         5000 non-null   float64
 8   hour_of_payment               5000 non-null   int64
 9   customer_tenure_days          5000 non-null   int64
 10  recovery_action               5000 non-null   str
 11  recovered                     5000 non-null   int64
 12  recovered_amount              5000 non-null   int64
dtypes: float64(1), int64(8), str(4)
memory usage: 507.9 KB

First 5 rows:

,payment_id,amount,payment_method,failure_reason,previous_successful_payments,previous_failed_payments,retry_count,customer_success_rate,hour_of_payment,customer_tenure_days,recovery_action,recovered,recovered_amount
0,PAY_00001,5472,UPI,Insufficient Funds,6,1,2,0.750,8,502,Reminder,0,0
1,PAY_00002,3090,UPI,User Abandoned,7,1,2,0.778,17,179,UPI Link,1,3090
2,PAY_00003,1858,UPI,Insufficient Funds,6,0,0,0.857,6,477,UPI Link,0,0
3,PAY_00004,510,UPI,Network Error,8,3,0,0.667,22,1331,UPI Link,0,0
4,PAY_00005,1059,Wallet,Bank Timeout,8,1,1,0.800,18,570,UPI Link,1,1059

In [31]:
# Select features and target

features = [
    "amount",
    "payment_method",
    "failure_reason",
    "previous_successful_payments",
    "previous_failed_payments",
    "retry_count",
    "customer_success_rate",
    "hour_of_payment",
    "customer_tenure_days"
]

X = df[features]
y = df["recovered"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nRecovery distribution:")
print(y.value_counts())

print("\nRecovery percentage:")
print(y.value_counts(normalize=True) * 100)

Feature shape: (5000, 9)
Target shape: (5000,)

Recovery distribution:
recovered
1    3074
0    1926
Name: count, dtype: int64

Recovery percentage:
recovered
1    61.48
0    38.52
Name: proportion, dtype: float64

In [ ]:
# Separate categorical and numerical features

# categorical_features = [
#     "payment_method",
    # "failure_reason"
# ]

# numerical_features = [
#     "amount",
#     "previous_successful_payments",
#     "previous_failed_payments",
#     "retry_count",
#     "customer_success_rate",
#     "hour_of_payment",
#     "customer_tenure_days"
# ]

# print("Categorical features:")
# print(categorical_features)

# print("\nNumerical features:")
# print(numerical_features)

Categorical features:
['payment_method', 'failure_reason']

Numerical features:
['amount', 'previous_successful_payments', 'previous_failed_payments', 'retry_count', 'customer_success_rate', 'hour_of_payment', 'customer_tenure_days']

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

# Preprocessing for numerical features
numerical_transformer = StandardScaler()

# Preprocessing for categorical features
categorical_transformer = OneHotEncoder(handle_unknown="ignore")

# Combine both transformations
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

print("Preprocessing pipeline created successfully!")

Preprocessing pipeline created successfully!

In [4]:
# Statistical summary
df.describe()

,amount,previous_successful_payments,previous_failed_payments,retry_count,customer_success_rate,hour_of_payment,customer_tenure_days,recovered,recovered_amount
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,5239.314600,8.056800,1.976000,0.687400,0.723425,11.492400,736.979800,0.614800,3140.264400
std,5947.385472,2.827503,1.439249,0.744441,0.122972,6.935529,436.121866,0.486691,4934.970635
min,200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,1872.750000,6.000000,1.000000,0.000000,0.643000,5.000000,352.750000,0.000000,0.000000
50%,3502.500000,8.000000,2.000000,1.000000,0.733000,11.000000,733.000000,1.000000,1552.500000
75%,6393.000000,10.000000,3.000000,1.000000,0.818000,18.000000,1118.000000,1.000000,4283.000000
max,100000.000000,21.000000,9.000000,2.000000,0.955000,23.000000,1500.000000,1.000000,75026.000000

In [5]:
for column in df.select_dtypes(include="object").columns:
    print(f"\n{column}")
    print(df[column].value_counts())

payment_id
payment_id
PAY_00001    1
PAY_00002    1
PAY_00003    1
PAY_00004    1
PAY_00005    1
            ..
PAY_04996    1
PAY_04997    1
PAY_04998    1
PAY_04999    1
PAY_05000    1
Name: count, Length: 5000, dtype: int64

payment_method
payment_method
Wallet         1299
UPI            1265
Card           1223
Net Banking    1213
Name: count, dtype: int64

failure_reason
failure_reason
Card Declined         868
Insufficient Funds    846
Bank Timeout          834
Technical Error       827
User Abandoned        825
Network Error         800
Name: count, dtype: int64

recovery_action
recovery_action
UPI Link    1877
Retry       1717
Reminder    1406
Name: count, dtype: int64

C:\Users\Kritika\AppData\Local\Temp\ipykernel_16152\526181458.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in df.select_dtypes(include="object").columns:

In [6]:
print(df.isnull().sum())

payment_id                      0
amount                          0
payment_method                  0
failure_reason                  0
previous_successful_payments    0
previous_failed_payments        0
retry_count                     0
customer_success_rate           0
hour_of_payment                 0
customer_tenure_days            0
recovery_action                 0
recovered                       0
recovered_amount                0
dtype: int64

In [7]:
# Drop columns that should not be used as features
X = df.drop(
    columns=[
        "payment_id",
        "recovered",
        "recovered_amount"
    ]
)

# Target
y = df["recovered"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (5000, 10)
Target shape: (5000,)

In [8]:
#  One-Hot Encoding.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Categorical columns
categorical_cols = [
    "payment_method",
    "failure_reason",
    "recovery_action"
]

# Numerical columns
numerical_cols = [
    "amount",
    "previous_successful_payments",
    "previous_failed_payments",
    "retry_count",
    "customer_success_rate",
    "hour_of_payment",
    "customer_tenure_days"
]

# Encoder
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_cols
        ),
        (
            "num",
            "passthrough",
            numerical_cols
        )
    ]
)

In [9]:
# test train split 

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (4000, 10)
Testing data: (1000, 10)

In [34]:
print(X_train.columns.tolist())

['amount', 'payment_method', 'failure_reason', 'previous_successful_payments', 'previous_failed_payments', 'retry_count', 'customer_success_rate', 'hour_of_payment', 'customer_tenure_days', 'recovery_action']

In [35]:
print("Training columns:")
print(X_train.columns.tolist())

Training columns:
['amount', 'payment_method', 'failure_reason', 'previous_successful_payments', 'previous_failed_payments', 'retry_count', 'customer_success_rate', 'hour_of_payment', 'customer_tenure_days', 'recovery_action']

In [36]:
from sklearn.linear_model import LogisticRegression

# Create ML pipeline
logistic_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", LogisticRegression(max_iter=1000))
    ]
)

# Train the model
logistic_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully!")

Logistic Regression model trained successfully!

In [10]:
# train logistic regression 
# data-> encoding-> logistic regression 

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

logistic_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            LogisticRegression(
                max_iter=1000,
                random_state=42
            )
        )
    ]
)

# Train model
logistic_model.fit(X_train, y_train)

c:\Users\Kritika\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['payment_method',
                                                   'failure_reason',
                                                   'recovery_action']),
                                                 ('num', 'passthrough',
                                                  ['amount',
                                                   'previous_successful_payments',
                                                   'previous_failed_payments',
                                                   'retry_count',
                                                   'customer_success_rate',
                                                   'hour_of_payment',
                                                   'customer_tenure_days'])])),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [11]:
# predictions
y_pred_logistic = logistic_model.predict(X_test)

# Probability
y_prob_logistic = logistic_model.predict_proba(X_test)[:, 1]

In [37]:
# evaluate logistic regression 

from sklearn.metrics import (
     accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

# Predictions
y_pred = logistic_model.predict(X_test)

# Recovery probabilities
y_prob = logistic_model.predict_proba(X_test)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.609
Precision: 0.6314553990610329
Recall: 0.8747967479674796
F1 Score: 0.7334696659850034
ROC-AUC Score: 0.5851251187836554

Classification Report:
              precision    recall  f1-score   support

           0       0.48      0.18      0.27       385
           1       0.63      0.87      0.73       615

    accuracy                           0.61      1000
   macro avg       0.56      0.53      0.50      1000
weighted avg       0.57      0.61      0.55      1000


Confusion Matrix:
[[ 71 314]
 [ 77 538]]

In [13]:
# Train random forest 
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "model",
            RandomForestClassifier(
                n_estimators=200,
                max_depth=12,
                random_state=42,
                n_jobs=-1
            )
        )
    ]
)

# Train
rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['payment_method',
                                                   'failure_reason',
                                                   'recovery_action']),
                                                 ('num', 'passthrough',
                                                  ['amount',
                                                   'previous_successful_payments',
                                                   'previous_failed_payments',
                                                   'retry_count',
                                                   'customer_success_rate',
                                                   'hour_of_payment',
                                                   'customer_tenure_days'])])),
                ('model',
                 RandomForestClassifier(max_depth=12, n_estimators=200,
                                        n_jobs=-1, random_state=42))])

In [14]:
y_pred_rf = rf_model.predict(X_test)

y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

In [15]:
# Evaluate Random forest
print("Random Forest Results\n")

print("Accuracy:",
      accuracy_score(y_test, y_pred_rf))

print("Precision:",
      precision_score(y_test, y_pred_rf))

print("Recall:",
      recall_score(y_test, y_pred_rf))

print("F1 Score:",
      f1_score(y_test, y_pred_rf))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Random Forest Results

Accuracy: 0.626
Precision: 0.6562905317769131
Recall: 0.8227642276422764
F1 Score: 0.7301587301587301

Classification Report:
              precision    recall  f1-score   support

           0       0.52      0.31      0.39       385
           1       0.66      0.82      0.73       615

    accuracy                           0.63      1000
   macro avg       0.59      0.57      0.56      1000
weighted avg       0.61      0.63      0.60      1000

In [16]:
# compare both models

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest"
    ],
    
    "Accuracy": [
        accuracy_score(y_test, y_pred_logistic),
        accuracy_score(y_test, y_pred_rf)
    ],
    
    "Precision": [
        precision_score(y_test, y_pred_logistic),
        precision_score(y_test, y_pred_rf)
    ],
    
    "Recall": [
        recall_score(y_test, y_pred_logistic),
        recall_score(y_test, y_pred_rf)
    ],
    
    "F1 Score": [
        f1_score(y_test, y_pred_logistic),
        f1_score(y_test, y_pred_rf)
    ]
})

print(results)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression     0.633   0.656566  0.845528  0.739161
1        Random Forest     0.626   0.656291  0.822764  0.730159

In [17]:
import joblib

joblib.dump(logistic_model, "payment_recovery_model.pkl")

print("Best model saved successfully!")

Best model saved successfully!

# Prediction

In [18]:
import pandas as pd
import joblib

# Load saved model
model = joblib.load("payment_recovery_model.pkl")

# Create a new failed payment
new_payment = pd.DataFrame([{
    "amount": 5000,
    "payment_method": "Card",
    "failure_reason": "Card Declined",
    "previous_successful_payments": 10,
    "previous_failed_payments": 1,
    "retry_count": 0,
    "customer_success_rate": 0.90,
    "hour_of_payment": 14,
    "customer_tenure_days": 500,
    "recovery_action": "UPI Link"
}])

# Predict recovery probability
probability = model.predict_proba(new_payment)[0][1]

print(f"Recovery Probability: {probability:.2%}")

Recovery Probability: 73.79%

# recovery agent

In [19]:
def choose_best_action(payment_details):
    
    # Actions our AI agent can choose
    actions = ["Retry", "UPI Link", "Reminder"]
    
    results = {}
    
    # Test each action
    for action in actions:
        
        # Copy the payment details
        payment_copy = payment_details.copy()
        
        # Add the action being tested
        payment_copy["recovery_action"] = action
        
        # Convert into DataFrame
        payment_df = pd.DataFrame([payment_copy])
        
        # Predict recovery probability
        probability = model.predict_proba(payment_df)[0][1]
        
        # Store result
        results[action] = probability
    
    # Find action with highest probability
    best_action = max(results, key=results.get)
    
    best_probability = results[best_action]
    
    return best_action, best_probability, results

In [20]:
payment_details = {
    "amount": 5000,
    "payment_method": "Card",
    "failure_reason": "Card Declined",
    "previous_successful_payments": 10,
    "previous_failed_payments": 1,
    "retry_count": 0,
    "customer_success_rate": 0.90,
    "hour_of_payment": 14,
    "customer_tenure_days": 500
}

best_action, best_probability, all_results = choose_best_action(
    payment_details
)

print(" AI RECOVERY AGENT")
print("-" * 30)

print("\nRecovery probabilities:")

for action, probability in all_results.items():
    print(f"{action}: {probability:.2%}")

print("\n BEST ACTION:", best_action)
print(f" Recovery Probability: {best_probability:.2%}")

 AI RECOVERY AGENT
------------------------------

Recovery probabilities:
Retry: 84.09%
UPI Link: 73.79%
Reminder: 69.53%

 BEST ACTION: Retry
 Recovery Probability: 84.09%

In [55]:
# AI Priority Function

def get_priority(payment_details, probability):

    amount = payment_details["amount"]

    # HIGH PRIORITY
    # High recovery probability + meaningful business value
    if probability >= 0.80 and amount >= 5000:
        return "HIGH"

    # High transaction value with reasonable recovery chance
    elif probability >= 0.60 and amount >= 20000:
        return "HIGH"

    # MEDIUM PRIORITY
    elif probability >= 0.50:
        return "MEDIUM"

    # LOW PRIORITY
    else:
        return "LOW"


def smart_recovery_agent(payment_details):

    # Available recovery actions
    actions = [
        "Retry",
        "UPI Link",
        "Reminder"
    ]

    # Safety rule:
    # If payment has already been retried 2 or more times,
    # do not recommend another retry
    if payment_details.get("retry_count", 0) >= 2:

        if "Retry" in actions:
            actions.remove("Retry")

    results = {}

    # Test every allowed recovery action
    for action in actions:

        # Create a copy so original payment data is not changed
        payment_copy = payment_details.copy()

        # Add current recovery action
        payment_copy["recovery_action"] = action

        # Convert to DataFrame for ML model
        payment_df = pd.DataFrame([
            payment_copy
        ])

        # Predict recovery probability
        probability = model.predict_proba(
            payment_df
        )[0][1]

        # Store probability for this action
        results[action] = float(probability)

    # Choose the action with highest probability
    best_action = max(
        results,
        key=results.get
    )

    best_probability = results[
        best_action
    ]

    # Calculate business priority
    priority = get_priority(
        payment_details,
        best_probability
    )

    return (
        best_action,
        best_probability,
        priority,
        results
    )

In [56]:
# Test
payment_details = {
    "amount": 5000,
    "payment_method": "Card",
    "failure_reason": "Card Declined",
    "previous_successful_payments": 10,
    "previous_failed_payments": 1,
    "retry_count": 0,
    "customer_success_rate": 0.90,
    "hour_of_payment": 14,
    "customer_tenure_days": 500
}

best_action, best_probability, priority, all_results = smart_recovery_agent(
    payment_details
)

print(" SMART AI RECOVERY AGENT")
print("-" * 35)

print("\nAll possible actions:")

for action, probability in all_results.items():
    print(f"{action}: {probability:.2%}")

print("\n BEST ACTION:", best_action)
print(f" Recovery Probability: {best_probability:.2%}")
print(" Priority:", priority)

 SMART AI RECOVERY AGENT
-----------------------------------

All possible actions:
Retry: 84.09%
UPI Link: 73.79%
Reminder: 69.53%

 BEST ACTION: Retry
 Recovery Probability: 84.09%
 Priority: HIGH

In [57]:
# retry_count =2

payment_details = {
    "amount": 5000,
    "payment_method": "Card",
    "failure_reason": "Card Declined",
    "previous_successful_payments": 10,
    "previous_failed_payments": 1,
    "retry_count": 2,  
    "customer_success_rate": 0.90,
    "hour_of_payment": 14,
    "customer_tenure_days": 500
}

best_action, best_probability, priority, all_results = smart_recovery_agent(
    payment_details
)

print(" SMART AI RECOVERY AGENT")
print("-" * 35)

print("\nAll possible actions:")

for action, probability in all_results.items():
    print(f"{action}: {probability:.2%}")

print("\n BEST ACTION:", best_action)
print(f" Recovery Probability: {best_probability:.2%}")
print(" Priority:", priority)

 SMART AI RECOVERY AGENT
-----------------------------------

All possible actions:
UPI Link: 59.17%
Reminder: 54.02%

 BEST ACTION: UPI Link
 Recovery Probability: 59.17%
 Priority: MEDIUM

In [24]:
# retry_count =4

payment_details = {
    "amount": 5000,
    "payment_method": "Card",
    "failure_reason": "Card Declined",
    "previous_successful_payments": 10,
    "previous_failed_payments": 1,
    "retry_count": 4,  
    "customer_success_rate": 0.90,
    "hour_of_payment": 14,
    "customer_tenure_days": 500
}

best_action, best_probability, priority, all_results = smart_recovery_agent(
    payment_details
)

print(" SMART AI RECOVERY AGENT")
print("-" * 35)

print("\nAll possible actions:")

for action, probability in all_results.items():
    print(f"{action}: {probability:.2%}")

print("\n BEST ACTION:", best_action)
print(f" Recovery Probability: {best_probability:.2%}")
print(" Priority:", priority)

 SMART AI RECOVERY AGENT
-----------------------------------

All possible actions:
UPI Link: 42.73%
Reminder: 37.69%

 BEST ACTION: UPI Link
 Recovery Probability: 42.73%
 Priority: LOW

RePay — Smart Payment Recovery

In [ ]:
import random
from datetime import datetime


def execute_recovery(payment_details):

    # Ask AI agent to choose the best action
    best_action, probability, priority, all_results = smart_recovery_agent(
        payment_details
    )

    # Convert probability to percentage
    confidence_percentage = round(
        probability * 100,
        2
    )

    # Expected recoverable revenue
    expected_recovery_amount = round(
        payment_details["amount"] * probability,
        2
    )

    # Generate AI reasoning
    reasoning = []

    reasoning.append(
        f"Predicted recovery probability is "
        f"{confidence_percentage}%."
    )

    reasoning.append(
        f"Recommended recovery action: {best_action}."
    )

    # Amount-based reasoning
    if payment_details["amount"] >= 10000:
        reasoning.append(
            "High transaction value increases business impact, "
            "so this payment should receive stronger attention."
        )

    # Historical customer behavior
    if payment_details.get(
        "previous_successful_payments", 0
    ) > payment_details.get(
        "previous_failed_payments", 0
    ):
        reasoning.append(
            "Customer has more successful payments than failed "
            "payments, indicating a higher likelihood of recovery."
        )

    # Retry reasoning
    if payment_details.get("retry_count", 0) >= 2:
        reasoning.append(
            "Multiple retry attempts were detected, so an "
            "alternative recovery method may be more suitable."
        )

    # Priority reasoning
    if priority == "HIGH":
        reasoning.append(
            "This payment is marked HIGH priority because of "
            "its recovery potential and business impact."
        )

    elif priority == "MEDIUM":
        reasoning.append(
            "This payment is marked MEDIUM priority and should "
            "be processed through the recommended recovery flow."
        )

    else:
        reasoning.append(
            "This payment is LOW priority because the predicted "
            "recovery potential is relatively limited."
        )

    # Create audit trail
    audit_trail = []

    current_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    # Payment failed event
    audit_trail.append({
        "time": current_time,
        "event": "Payment failed"
    })

    # AI analysis
    audit_trail.append({
        "time": current_time,
        "event": (
            f"AI analyzed payment and predicted "
            f"{confidence_percentage}% recovery probability"
        )
    })

    # Selected action
    audit_trail.append({
        "time": current_time,
        "event": (
            f"AI selected recovery action: "
            f"{best_action}"
        )
    })

    # Priority assigned
    audit_trail.append({
        "time": current_time,
        "event": (
            f"Payment assigned {priority} priority"
        )
    })

    # Simulate recovery based on ML probability
    recovered = random.random() < probability

    if recovered:

        recovered_amount = payment_details["amount"]

        status = "RECOVERED"

    else:

        recovered_amount = 0

        status = "NOT RECOVERED"

    # Final event
    audit_trail.append({
        "time": datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        ),
        "event": (
            f"Recovery result: {status}"
        )
    })

    return {

        # AI decision
        "best_action": best_action,

        # ML prediction
        "recovery_probability": probability,

        "confidence_percentage": confidence_percentage,

        # Business priority
        "priority": priority,

        # Expected revenue
        "expected_recovery_amount":
            expected_recovery_amount,

        # Explainable AI reasoning
        "reasoning": reasoning,

        # Recovery result
        "status": status,

        "recovered_amount":
            recovered_amount,

        # Alternative predictions
        "all_predictions":
            all_results,

        # Complete event history
        "audit_trail":
            audit_trail
    }

In [46]:
test_payment = {
    "amount": 5000,
    "payment_method": "Card",
    "failure_reason": "Card Declined",
    "previous_successful_payments": 10,
    "previous_failed_payments": 1,
    "retry_count": 0,
    "customer_success_rate": 0.90,
    "hour_of_payment": 14,
    "customer_tenure_days": 500
}

result = execute_recovery(test_payment)

print(" RePay — Smart Payment Recovery RESULT")
print("=" * 45)

print(f"\nBest Action: {result['best_action']}")
print(f"Recovery Probability: {result['recovery_probability']:.2%}")
print(f"Priority: {result['priority']}")
print(f"Final Status: {result['status']}")
print(f"Revenue Recovered: ₹{result['recovered_amount']}")

print("\n AUDIT TRAIL")
print("-" * 45)

for event in result["audit_trail"]:
    print(f"{event['time']} | {event['event']}")

 RePay — Smart Payment Recovery RESULT
=============================================

Best Action: Retry
Recovery Probability: 84.09%
Priority: HIGH
Final Status: RECOVERED
Revenue Recovered: ₹5000

 AUDIT TRAIL
---------------------------------------------
2026-08-26 21:23:04 | Payment failed
2026-08-26 21:23:04 | AI analyzed payment and predicted 84.09% recovery probability
2026-08-26 21:23:04 | AI selected recovery action: Retry
2026-08-26 21:23:04 | Payment assigned HIGH  priority
2026-08-26 21:23:04 | Recovery result: RECOVERED

In [58]:
# process multiple payments 

# Process Multiple Payments

import pandas as pd
from datetime import datetime


def process_multiple_payments(payments):

    results = []

    for payment in payments:

        # -----------------------------------
        # Run complete AI recovery workflow
        # -----------------------------------

        result = execute_recovery(payment)


        # -----------------------------------
        # Current processing time
        # -----------------------------------

        processed_time = datetime.now()


        # -----------------------------------
        # Store payment + AI results
        # -----------------------------------

        results.append({

            # Basic payment information
            "amount": payment["amount"],

            "payment_method": payment["payment_method"],

            "failure_reason": payment["failure_reason"],


            # -----------------------------------
            # AI Decision
            # -----------------------------------

            "best_action": result["best_action"],


            # -----------------------------------
            # ML Prediction
            # -----------------------------------

            "recovery_probability": result[
                "recovery_probability"
            ],

            "confidence_percentage": result[
                "confidence_percentage"
            ],


            # -----------------------------------
            # Business Priority
            # -----------------------------------

            "priority": result["priority"],


            # -----------------------------------
            # Revenue Intelligence
            # -----------------------------------

            "expected_recovery_amount": result[
                "expected_recovery_amount"
            ],


            "recovered_amount": result[
                "recovered_amount"
            ],


            # -----------------------------------
            # Explainable AI
            # -----------------------------------

            "ai_reasoning": result.get(
                "reasoning",
                [
                    "AI analyzed payment behavior and "
                    "selected the best recovery strategy."
                ]
            ),


            # -----------------------------------
            # Alternative action predictions
            # -----------------------------------

            "all_predictions": result.get(
                "all_predictions",
                {}
            ),


            # -----------------------------------
            # Audit Trail
            # -----------------------------------

            "audit_trail": result.get(
                "audit_trail",
                []
            ),


            # -----------------------------------
            # Recovery Status
            # -----------------------------------

            "status": result["status"],


            # -----------------------------------
            # Timestamps
            # -----------------------------------

            "created_at": processed_time,


            "recovered_at": (
                processed_time
                if result["status"] == "RECOVERED"
                else None
            )

        })


    # -----------------------------------
    # Return all processed payments
    # -----------------------------------

    return pd.DataFrame(results)

In [59]:
batch_results = process_multiple_payments(payments)

batch_results

,amount,payment_method,failure_reason,best_action,recovery_probability,confidence_percentage,priority,expected_recovery_amount,recovered_amount,ai_reasoning,all_predictions,audit_trail,status,created_at,recovered_at
0,5000,Card,Card Declined,Retry,0.840890,84.09,HIGH,4204.45,5000,"[Predicted recovery probability is 84.09%., Re...","{'Retry': 0.840889719867961, 'UPI Link': 0.737...","[{'time': '2026-08-26 21:35:29', 'event': 'Pay...",RECOVERED,2026-08-26 21:35:29.344376,2026-08-26 21:35:29.344376
1,12000,UPI,Bank Timeout,Retry,0.841795,84.18,HIGH,10101.54,12000,"[Predicted recovery probability is 84.18%., Re...","{'Retry': 0.8417949878011772, 'UPI Link': 0.73...","[{'time': '2026-08-26 21:35:29', 'event': 'Pay...",RECOVERED,2026-08-26 21:35:29.372266,2026-08-26 21:35:29.372266
2,2500,Wallet,User Abandoned,Retry,0.638979,63.90,MEDIUM,1597.45,0,"[Predicted recovery probability is 63.9%., Rec...","{'Retry': 0.6389787670067725, 'UPI Link': 0.48...","[{'time': '2026-08-26 21:35:29', 'event': 'Pay...",NOT RECOVERED,2026-08-26 21:35:29.381123,NaT
3,8000,Card,Technical Error,UPI Link,0.539417,53.94,MEDIUM,4315.33,8000,"[Predicted recovery probability is 53.94%., Re...","{'UPI Link': 0.5394167482386036, 'Reminder': 0...","[{'time': '2026-08-26 21:35:29', 'event': 'Pay...",RECOVERED,2026-08-26 21:35:29.381123,2026-08-26 21:35:29.381123
4,30000,Net Banking,Insufficient Funds,UPI Link,0.112779,11.28,LOW,3383.38,0,"[Predicted recovery probability is 11.28%., Re...","{'UPI Link': 0.11277927125243746, 'Reminder': ...","[{'time': '2026-08-26 21:35:29', 'event': 'Pay...",NOT RECOVERED,2026-08-26 21:35:29.398703,NaT

In [48]:
# test

payments = [
    {
        "amount": 5000,
        "payment_method": "Card",
        "failure_reason": "Card Declined",
        "previous_successful_payments": 10,
        "previous_failed_payments": 1,
        "retry_count": 0,
        "customer_success_rate": 0.90,
        "hour_of_payment": 14,
        "customer_tenure_days": 500
    },
    
    {
        "amount": 12000,
        "payment_method": "UPI",
        "failure_reason": "Bank Timeout",
        "previous_successful_payments": 20,
        "previous_failed_payments": 2,
        "retry_count": 0,
        "customer_success_rate": 0.90,
        "hour_of_payment": 10,
        "customer_tenure_days": 800
    },
    
    {
        "amount": 2500,
        "payment_method": "Wallet",
        "failure_reason": "User Abandoned",
        "previous_successful_payments": 3,
        "previous_failed_payments": 4,
        "retry_count": 1,
        "customer_success_rate": 0.40,
        "hour_of_payment": 22,
        "customer_tenure_days": 100
    },
    
    {
        "amount": 8000,
        "payment_method": "Card",
        "failure_reason": "Technical Error",
        "previous_successful_payments": 15,
        "previous_failed_payments": 1,
        "retry_count": 2,
        "customer_success_rate": 0.88,
        "hour_of_payment": 16,
        "customer_tenure_days": 600
    },
    
    {
        "amount": 30000,
        "payment_method": "Net Banking",
        "failure_reason": "Insufficient Funds",
        "previous_successful_payments": 2,
        "previous_failed_payments": 8,
        "retry_count": 2,
        "customer_success_rate": 0.20,
        "hour_of_payment": 20,
        "customer_tenure_days": 50
    }
]

In [29]:
batch_results = process_multiple_payments(payments)

batch_results

,amount,payment_method,failure_reason,best_action,recovery_probability,priority,status,recovered_amount
0,5000,Card,Card Declined,Retry,0.840890,HIGH,RECOVERED,5000
1,12000,UPI,Bank Timeout,Retry,0.841795,HIGH,RECOVERED,12000
2,2500,Wallet,User Abandoned,Retry,0.638979,MEDIUM,NOT RECOVERED,0
3,8000,Card,Technical Error,UPI Link,0.539417,MEDIUM,RECOVERED,8000
4,30000,Net Banking,Insufficient Funds,UPI Link,0.112779,LOW,NOT RECOVERED,0

In [49]:
print(batch_results.columns.tolist())

batch_results.head()

['amount', 'payment_method', 'failure_reason', 'best_action', 'recovery_probability', 'priority', 'status', 'recovered_amount', 'expected_recovery_value', 'normalized_amount', 'business_priority_score', 'business_priority', 'ai_reasoning']

,amount,payment_method,failure_reason,best_action,recovery_probability,priority,status,recovered_amount,expected_recovery_value,normalized_amount,business_priority_score,business_priority,ai_reasoning
0,5000,Card,Card Declined,Retry,0.840890,HIGH,RECOVERED,5000,4204.448599,0.166667,0.638623,MEDIUM,High recovery likelihood (84.1%). Retry is pre...
1,12000,UPI,Bank Timeout,Retry,0.841795,HIGH,RECOVERED,12000,10101.539854,0.400000,0.709256,HIGH,High recovery likelihood (84.2%). High transac...
2,2500,Wallet,User Abandoned,Retry,0.638979,MEDIUM,NOT RECOVERED,0,1597.446918,0.083333,0.472285,MEDIUM,Moderate recovery likelihood (63.9%). Retry is...
3,8000,Card,Technical Error,UPI Link,0.539417,MEDIUM,RECOVERED,8000,4315.333986,0.266667,0.457592,MEDIUM,Moderate recovery likelihood (53.9%). UPI Link...
4,30000,Net Banking,Insufficient Funds,UPI Link,0.112779,LOW,NOT RECOVERED,0,3383.378138,1.000000,0.378945,LOW,Lower recovery likelihood (11.3%). High transa...

In [50]:

# EXPECTED RECOVERY VALUE


batch_results["expected_recovery_value"] = (
    batch_results["amount"]
    * batch_results["recovery_probability"]
)

batch_results[
    [
        "amount",
        "recovery_probability",
        "expected_recovery_value"
    ]
].head()

   amount  recovery_probability  expected_recovery_value
0    5000              0.840890              4204.448599
1   12000              0.841795             10101.539854
2    2500              0.638979              1597.446918
3    8000              0.539417              4315.333986
4   30000              0.112779              3383.378138

In [51]:

# BUSINESS-AWARE PRIORITY SCORE


# Normalize transaction amount between 0 and 1
max_amount = batch_results["amount"].max()

batch_results["normalized_amount"] = (
    batch_results["amount"] / max_amount
)

# Priority Score
# 70% importance -> recovery likelihood
# 30% importance -> financial impact

batch_results["business_priority_score"] = (
    0.70 * batch_results["recovery_probability"]
    +
    0.30 * batch_results["normalized_amount"]
)

batch_results[
    [
        "amount",
        "recovery_probability",
        "business_priority_score"
    ]
].head()

   amount  recovery_probability  business_priority_score
0    5000              0.840890                 0.638623
1   12000              0.841795                 0.709256
2    2500              0.638979                 0.472285
3    8000              0.539417                 0.457592
4   30000              0.112779                 0.378945

In [41]:

# ASSIGN BUSINESS PRIORITY


def assign_business_priority(score):

    if score >= 0.70:
        return "HIGH"

    elif score >= 0.45:
        return "MEDIUM"

    else:
        return "LOW"


batch_results["business_priority"] = (
    batch_results["business_priority_score"]
    .apply(assign_business_priority)
)

batch_results[
    [
        "amount",
        "recovery_probability",
        "business_priority_score",
        "business_priority"
    ]
].head(10)

   amount  recovery_probability  business_priority_score business_priority
0    5000              0.840890                 0.638623            MEDIUM
1   12000              0.841795                 0.709256              HIGH
2    2500              0.638979                 0.472285            MEDIUM
3    8000              0.539417                 0.457592            MEDIUM
4   30000              0.112779                 0.378945               LOW

In [42]:

# EXPLAINABLE AI DECISION REASONING


high_value_threshold = (
    batch_results["amount"].quantile(0.75)
)


def generate_ai_reasoning(row):

    reasons = []

    probability = row["recovery_probability"] * 100

    # Recovery likelihood
    if probability >= 80:

        reasons.append(
            f"High recovery likelihood ({probability:.1f}%)"
        )

    elif probability >= 50:

        reasons.append(
            f"Moderate recovery likelihood ({probability:.1f}%)"
        )

    else:

        reasons.append(
            f"Lower recovery likelihood ({probability:.1f}%)"
        )


    # Financial impact
    if row["amount"] >= high_value_threshold:

        reasons.append(
            f"High transaction value of ₹{row['amount']:,.0f} increases business impact"
        )


    # Recovery action reasoning
    if row["best_action"] == "Retry":

        reasons.append(
            "Retry is predicted to be the most effective recovery action"
        )

    elif row["best_action"] == "UPI Link":

        reasons.append(
            "UPI Link is predicted to provide a better alternative recovery path"
        )

    elif row["best_action"] == "Reminder":

        reasons.append(
            "Reminder is selected as the most suitable customer follow-up action"
        )


    # Final priority explanation
    if row["business_priority"] == "HIGH":

        reasons.append(
            "High expected business recovery opportunity"
        )

    elif row["business_priority"] == "MEDIUM":

        reasons.append(
            "Moderate recovery opportunity"
        )

    else:

        reasons.append(
            "Lower recovery opportunity compared with other failed payments"
        )


    return ". ".join(reasons) + "."


batch_results["ai_reasoning"] = (
    batch_results.apply(
        generate_ai_reasoning,
        axis=1
    )
)


batch_results[
    [
        "amount",
        "best_action",
        "recovery_probability",
        "expected_recovery_value",
        "business_priority",
        "ai_reasoning"
    ]
].head()

,amount,best_action,recovery_probability,expected_recovery_value,business_priority,ai_reasoning
0,5000,Retry,0.840890,4204.448599,MEDIUM,High recovery likelihood (84.1%). Retry is pre...
1,12000,Retry,0.841795,10101.539854,HIGH,High recovery likelihood (84.2%). High transac...
2,2500,Retry,0.638979,1597.446918,MEDIUM,Moderate recovery likelihood (63.9%). Retry is...
3,8000,UPI Link,0.539417,4315.333986,MEDIUM,Moderate recovery likelihood (53.9%). UPI Link...
4,30000,UPI Link,0.112779,3383.378138,LOW,Lower recovery likelihood (11.3%). High transa...

In [44]:
# dashboard metrics

# RePay Dashboard Metrics

total_payments = len(batch_results)

# Total failed payment value
total_revenue_at_risk = (
    batch_results["amount"].sum()
)

# Number of recovered payments
recovered_payments = (
    batch_results["status"] == "RECOVERED"
).sum()

# Actual recovered revenue
total_revenue_recovered = (
    batch_results["recovered_amount"].sum()
)

# Recovery rate
recovery_rate = (
    recovered_payments / total_payments
) * 100 if total_payments > 0 else 0


# Expected recoverable revenue based on ML confidence
expected_recovery_revenue = (
    batch_results["amount"]
    * batch_results["recovery_probability"]
).sum()


# High priority payments
high_priority_count = (
    batch_results["priority"] == "HIGH"
).sum()


# Average AI confidence
average_recovery_probability = (
    batch_results["recovery_probability"].mean()
    * 100
)


print("RePay — AI Payment Recovery Dashboard")
print("=" * 50)

print(f"Total Failed Payments: {total_payments}")

print(
    f"Total Revenue at Risk: "
    f"₹{total_revenue_at_risk:,.2f}"
)

print(f"Recovered Payments: {recovered_payments}")

print(
    f"Revenue Recovered: "
    f"₹{total_revenue_recovered:,.2f}"
)

print(
    f"Expected Recoverable Revenue: "
    f"₹{expected_recovery_revenue:,.2f}"
)

print(
    f"Recovery Rate: "
    f"{recovery_rate:.2f}%"
)

print(
    f"High Priority Payments: "
    f"{high_priority_count}"
)

print(
    f"Average AI Recovery Confidence: "
    f"{average_recovery_probability:.2f}%"
)

RePay — AI Payment Recovery Dashboard
==================================================
Total Failed Payments: 5
Total Revenue at Risk: ₹57,500.00
Recovered Payments: 3
Revenue Recovered: ₹25,000.00
Expected Recoverable Revenue: ₹23,602.15
Recovery Rate: 60.00%
High Priority Payments: 0
Average AI Recovery Confidence: 59.48%

RePay
Recover. Retry. RePay.